name: docs_pages_workflow
 
# execute this workflow automatically when a we push to master
on:
  push:
    branches: [ main ]
 
jobs:
 
  build_docs_job:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
 
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.9
 
      - name: Install dependencies
#        run: python -m pip install -U sphinx
        run: sudo apt-get -y install python3-sphinx python3-sphinx-rtd-theme
      
      - name: Clean
        run: make -C docs clean
      
      - name: Make html
        run: make -C docs html
        
      - name: Set up Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          
      - name: Commit all changes
        run: |
          git add -A && git commit -m 'Build site' || echo "No changes to commit"
          git push origin || echo "No changes to commit"

